"""add report envelope aliases

Revision ID: 09885b1699a9
Revises: 9e5ff689fc8c
Create Date: 2025-12-21 23:42:27.896250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09885b1699a9'
down_revision: Union[str, None] = '9e5ff689fc8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_envelope_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.TEXT(), nullable=False),
    sa.Column('envelope_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.TEXT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['envelope_id'], ['envelopes.id'], name='report_envelope_alias_envelope_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='report_envelope_alias_user_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_envelope_aliases_envelope_id'), 'report_envelope_aliases', ['envelope_id'], unique=False)
    op.create_index(op.f('ix_report_envelope_aliases_report_type'), 'report_envelope_aliases', ['report_type'], unique=False)
    op.create_index(op.f('ix_report_envelope_aliases_user_id'), 'report_envelope_aliases', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_envelope_aliases_user_id'), table_name='report_envelope_aliases')
    op.drop_index(op.f('ix_report_envelope_aliases_report_type'), table_name='report_envelope_aliases')
    op.drop_index(op.f('ix_report_envelope_aliases_envelope_id'), table_name='report_envelope_aliases')
    op.drop_table('report_envelope_aliases')
    # ### end Alembic commands ###
