"""add linked stripe id

Revision ID: 30ee5a72b0cc
Revises: a0ab344c0d2a
Create Date: 2025-11-28 19:12:18.061178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ee5a72b0cc'
down_revision: Union[str, None] = 'a0ab344c0d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_email_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('subscribed_at', sa.BIGINT(), nullable=False),
    sa.Column('unsubscribed_at', sa.BIGINT(), nullable=True),
    sa.Column('email_type', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_subscription_user_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_subscriptions')
    op.add_column('users', sa.Column('linked_stripe_id', sa.TEXT(), nullable=True))
    op.create_unique_constraint(None, 'users', ['linked_stripe_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'linked_stripe_id')
    op.create_table('user_subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('subscribed_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('unsubscribed_at', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('email_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_subscription_user_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_subscriptions_pkey'))
    )
    op.drop_table('user_email_subscriptions')
    # ### end Alembic commands ###
