"""make report aliases unique

Revision ID: 3d1b311733c1
Revises: 09885b1699a9
Create Date: 2025-12-21 23:44:31.377714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d1b311733c1'
down_revision: Union[str, None] = '09885b1699a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_report_envelope_alias_user_report_envelope', 'report_envelope_aliases', ['user_id', 'report_type', 'envelope_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_report_envelope_alias_user_report_envelope', 'report_envelope_aliases', type_='unique')
    # ### end Alembic commands ###
