"""nullable entities

Revision ID: 4e4f3fba9a9a
Revises: a1b692fb019c
Create Date: 2025-12-21 15:14:36.366046

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e4f3fba9a9a"
down_revision: Union[str, None] = "a1b692fb019c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    tables = [
        "accounts",
        "entities",
        "envelopes",
        "transactions",
    ]

    for table in tables:
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("accounts", "entity_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("envelopes", "entity_id", existing_type=sa.UUID(), nullable=True)
    op.drop_index(op.f("ix_envelopes_type"), table_name="envelopes")
    op.drop_column("envelopes", "type")
    op.add_column("payees", sa.Column("entity_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "payee_entity_fkey",
        "payees",
        "entities",
        ["entity_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###

    for table in tables:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("payee_entity_fkey", "payees", type_="foreignkey")
    op.drop_column("payees", "entity_id")
    op.add_column(
        "envelopes", sa.Column("type", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.create_index(op.f("ix_envelopes_type"), "envelopes", ["type"], unique=False)
    op.alter_column("envelopes", "entity_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("accounts", "entity_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
