"""add type to envelope

Revision ID: 64b4319a2df2
Revises: a6ad18c02c9f
Create Date: 2025-11-29 14:44:34.168657

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "64b4319a2df2"
down_revision: Union[str, None] = "a6ad18c02c9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("transaction_account_fkey"), "transactions", type_="foreignkey"
    )
    op.execute("ALTER TABLE envelopes NO FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE transactions NO FORCE ROW LEVEL SECURITY;")
    op.drop_table("accounts")
    op.add_column("envelopes", sa.Column("type", sa.TEXT(), nullable=False))
    op.create_index(op.f("ix_envelopes_type"), "envelopes", ["type"], unique=False)
    op.add_column("transactions", sa.Column("from_id", sa.UUID(), nullable=True))
    op.add_column("transactions", sa.Column("to_id", sa.UUID(), nullable=True))
    op.drop_constraint(
        op.f("transaction_envelope_fkey"), "transactions", type_="foreignkey"
    )
    op.create_foreign_key(
        "transaction_to_envelope_fkey",
        "transactions",
        "envelopes",
        ["to_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "transaction_from_envelope_fkey",
        "transactions",
        "envelopes",
        ["from_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("transactions", "account_id")
    op.drop_column("transactions", "envelope_id")
    op.execute("ALTER TABLE envelopes FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE transactions FORCE ROW LEVEL SECURITY;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("envelope_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "transactions",
        sa.Column("account_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        "transaction_from_envelope_fkey", "transactions", type_="foreignkey"
    )
    op.drop_constraint(
        "transaction_to_envelope_fkey", "transactions", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("transaction_account_fkey"),
        "transactions",
        "accounts",
        ["account_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("transaction_envelope_fkey"),
        "transactions",
        "envelopes",
        ["envelope_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("transactions", "to_id")
    op.drop_column("transactions", "from_id")
    op.drop_index(op.f("ix_envelopes_type"), table_name="envelopes")
    op.drop_column("envelopes", "type")
    op.create_table(
        "accounts",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("entity_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("account_entity_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("account_user_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("accounts_pkey")),
    )
    # ### end Alembic commands ###
