"""rename created and updated date fields

Revision ID: 70b51dff642a
Revises: cfd8a644c5e8
Create Date: 2025-12-21 16:00:49.014691

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "70b51dff642a"
down_revision: Union[str, None] = "cfd8a644c5e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;")
    op.add_column(
        "transactions",
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "transactions",
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.drop_column("transactions", "updated_in_exchequer_at")
    op.drop_column("transactions", "created_in_exchequer_at")
    op.execute("ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "created_in_exchequer_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "transactions",
        sa.Column(
            "updated_in_exchequer_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("transactions", "updated_at")
    op.drop_column("transactions", "created_at")
    # ### end Alembic commands ###
