"""add import source

Revision ID: 72709ad374f2
Revises: b2b509d76d4c
Create Date: 2025-12-21 14:14:15.851845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72709ad374f2'
down_revision: Union[str, None] = 'b2b509d76d4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('import_source', sa.TEXT(), nullable=True))
    op.create_index(op.f('ix_accounts_import_source'), 'accounts', ['import_source'], unique=False)
    op.add_column('envelopes', sa.Column('import_source', sa.TEXT(), nullable=True))
    op.create_index(op.f('ix_envelopes_import_source'), 'envelopes', ['import_source'], unique=False)
    op.add_column('payees', sa.Column('import_source', sa.TEXT(), nullable=True))
    op.create_index(op.f('ix_payees_import_source'), 'payees', ['import_source'], unique=False)
    op.add_column('plans', sa.Column('import_source', sa.TEXT(), nullable=True))
    op.add_column('transactions', sa.Column('import_source', sa.TEXT(), nullable=True))
    op.create_index(op.f('ix_transactions_import_source'), 'transactions', ['import_source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_import_source'), table_name='transactions')
    op.drop_column('transactions', 'import_source')
    op.drop_column('plans', 'import_source')
    op.drop_index(op.f('ix_payees_import_source'), table_name='payees')
    op.drop_column('payees', 'import_source')
    op.drop_index(op.f('ix_envelopes_import_source'), table_name='envelopes')
    op.drop_column('envelopes', 'import_source')
    op.drop_index(op.f('ix_accounts_import_source'), table_name='accounts')
    op.drop_column('accounts', 'import_source')
    # ### end Alembic commands ###
