"""make account nullable

Revision ID: 9e5ff689fc8c
Revises: 9efa4773e98a
Create Date: 2025-12-21 16:03:19.208632

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e5ff689fc8c"
down_revision: Union[str, None] = "9efa4773e98a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;")
    op.alter_column(
        "transactions", "account_id", existing_type=sa.UUID(), nullable=True
    )
    op.execute("ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions", "account_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
