"""make entity id nullable

Revision ID: 9efa4773e98a
Revises: 70b51dff642a
Create Date: 2025-12-21 16:02:33.734617

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9efa4773e98a"
down_revision: Union[str, None] = "70b51dff642a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;")
    op.alter_column("transactions", "entity_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###

    op.execute("ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions", "entity_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
