"""Add unique index to tables

Revision ID: a1b692fb019c
Revises: 72709ad374f2
Create Date: 2025-12-21 14:44:05.387189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b692fb019c'
down_revision: Union[str, None] = '72709ad374f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_import_id'), table_name='accounts')
    op.create_index(op.f('ix_accounts_import_id'), 'accounts', ['import_id'], unique=True)
    op.drop_index(op.f('ix_envelopes_import_id'), table_name='envelopes')
    op.create_index(op.f('ix_envelopes_import_id'), 'envelopes', ['import_id'], unique=True)
    op.drop_index(op.f('ix_payees_import_id'), table_name='payees')
    op.create_index(op.f('ix_payees_import_id'), 'payees', ['import_id'], unique=True)
    op.drop_index(op.f('ix_transactions_import_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_import_id'), 'transactions', ['import_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_import_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_import_id'), 'transactions', ['import_id'], unique=False)
    op.drop_index(op.f('ix_payees_import_id'), table_name='payees')
    op.create_index(op.f('ix_payees_import_id'), 'payees', ['import_id'], unique=False)
    op.drop_index(op.f('ix_envelopes_import_id'), table_name='envelopes')
    op.create_index(op.f('ix_envelopes_import_id'), 'envelopes', ['import_id'], unique=False)
    op.drop_index(op.f('ix_accounts_import_id'), table_name='accounts')
    op.create_index(op.f('ix_accounts_import_id'), 'accounts', ['import_id'], unique=False)
    # ### end Alembic commands ###
