"""add date fields to plans

Revision ID: b2b509d76d4c
Revises: 795862923dd4
Create Date: 2025-12-20 23:48:25.210927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2b509d76d4c'
down_revision: Union[str, None] = '795862923dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('plans', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'updated_at')
    op.drop_column('plans', 'created_at')
    # ### end Alembic commands ###
