"""adds more basic table types

Revision ID: bfba9d607088
Revises: cb9e6eb58c65
Create Date: 2025-12-20 23:15:03.283618

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bfba9d607088"
down_revision: Union[str, None] = "cb9e6eb58c65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    tables = [
        "entities",
        "envelopes",
        "transactions",
    ]

    for table in tables:
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency_formats",
        sa.Column("currency_code", sa.TEXT(), nullable=False),
        sa.Column("symbol", sa.TEXT(), nullable=False),
        sa.Column("symbol_position", sa.TEXT(), nullable=False),
        sa.Column("decimal_separator", sa.TEXT(), nullable=False),
        sa.Column("thousand_separator", sa.TEXT(), nullable=False),
        sa.Column("decimal_places", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("currency_code"),
    )
    op.create_table(
        "payees",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("import_revision", sa.INTEGER(), nullable=True),
        sa.Column("import_id", sa.TEXT(), nullable=True),
        sa.Column(
            "imported_document", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="payee_user_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payees_import_id"), "payees", ["import_id"], unique=False)
    op.create_index(
        op.f("ix_payees_import_revision"), "payees", ["import_revision"], unique=False
    )
    op.create_table(
        "plans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("currency_code", sa.TEXT(), nullable=False),
        sa.Column("amount", sa.NUMERIC(precision=17, scale=3), nullable=False),
        sa.ForeignKeyConstraint(
            ["currency_code"],
            ["currency_formats.currency_code"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="plan_user_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.TEXT(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("import_revision", sa.INTEGER(), nullable=True),
        sa.Column("import_id", sa.TEXT(), nullable=True),
        sa.Column(
            "imported_document", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name="account_entity_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="account_user_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_accounts_import_id"), "accounts", ["import_id"], unique=False
    )
    op.create_index(
        op.f("ix_accounts_import_revision"),
        "accounts",
        ["import_revision"],
        unique=False,
    )
    op.create_index(op.f("ix_accounts_type"), "accounts", ["type"], unique=False)
    op.add_column(
        "envelopes", sa.Column("import_revision", sa.INTEGER(), nullable=True)
    )
    op.add_column("envelopes", sa.Column("import_id", sa.TEXT(), nullable=True))
    op.add_column(
        "envelopes",
        sa.Column(
            "imported_document", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.create_index(
        op.f("ix_envelopes_import_id"), "envelopes", ["import_id"], unique=False
    )
    op.create_index(
        op.f("ix_envelopes_import_revision"),
        "envelopes",
        ["import_revision"],
        unique=False,
    )
    op.add_column("transactions", sa.Column("account_id", sa.UUID(), nullable=False))
    op.add_column(
        "transactions", sa.Column("transfer_account_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "transactions", sa.Column("transfer_transaction_id", sa.UUID(), nullable=True)
    )
    op.add_column("transactions", sa.Column("envelope_id", sa.UUID(), nullable=True))
    op.add_column(
        "transactions", sa.Column("import_revision", sa.INTEGER(), nullable=True)
    )
    op.add_column("transactions", sa.Column("import_id", sa.TEXT(), nullable=True))
    op.add_column(
        "transactions",
        sa.Column(
            "imported_document", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.create_index(
        op.f("ix_transactions_import_id"), "transactions", ["import_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_import_revision"),
        "transactions",
        ["import_revision"],
        unique=False,
    )
    op.drop_constraint(
        op.f("transaction_to_envelope_fkey"), "transactions", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("transaction_from_envelope_fkey"), "transactions", type_="foreignkey"
    )
    op.create_foreign_key(
        "transaction_envelope_fkey",
        "transactions",
        "envelopes",
        ["envelope_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "transaction_account_fkey",
        "transactions",
        "accounts",
        ["account_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "transaction_transfer_account_fkey",
        "transactions",
        "accounts",
        ["transfer_account_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "transaction_transfer_transaction_fkey",
        "transactions",
        "transactions",
        ["transfer_transaction_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("transactions", "from_id")
    op.drop_column("transactions", "to_id")
    # ### end Alembic commands ###

    for table in tables:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("to_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "transactions",
        sa.Column("from_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        "transaction_transfer_transaction_fkey", "transactions", type_="foreignkey"
    )
    op.drop_constraint(
        "transaction_transfer_account_fkey", "transactions", type_="foreignkey"
    )
    op.drop_constraint("transaction_account_fkey", "transactions", type_="foreignkey")
    op.drop_constraint("transaction_envelope_fkey", "transactions", type_="foreignkey")
    op.create_foreign_key(
        op.f("transaction_from_envelope_fkey"),
        "transactions",
        "envelopes",
        ["from_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("transaction_to_envelope_fkey"),
        "transactions",
        "envelopes",
        ["to_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_transactions_import_revision"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_import_id"), table_name="transactions")
    op.drop_column("transactions", "imported_document")
    op.drop_column("transactions", "import_id")
    op.drop_column("transactions", "import_revision")
    op.drop_column("transactions", "envelope_id")
    op.drop_column("transactions", "transfer_transaction_id")
    op.drop_column("transactions", "transfer_account_id")
    op.drop_column("transactions", "account_id")
    op.drop_index(op.f("ix_envelopes_import_revision"), table_name="envelopes")
    op.drop_index(op.f("ix_envelopes_import_id"), table_name="envelopes")
    op.drop_column("envelopes", "imported_document")
    op.drop_column("envelopes", "import_id")
    op.drop_column("envelopes", "import_revision")
    op.drop_index(op.f("ix_accounts_type"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_import_revision"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_import_id"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_table("plans")
    op.drop_index(op.f("ix_payees_import_revision"), table_name="payees")
    op.drop_index(op.f("ix_payees_import_id"), table_name="payees")
    op.drop_table("payees")
    op.drop_table("currency_formats")
    # ### end Alembic commands ###
