"""add payee

Revision ID: cfd8a644c5e8
Revises: f6f05cc3682d
Create Date: 2025-12-21 15:58:41.415422

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cfd8a644c5e8"
down_revision: Union[str, None] = "f6f05cc3682d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("payee_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "transaction_payee_fkey",
        "transactions",
        "payees",
        ["payee_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.execute("ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("transaction_payee_fkey", "transactions", type_="foreignkey")
    op.drop_column("transactions", "payee_id")
    # ### end Alembic commands ###
