"""add fields to account

Revision ID: d6e180c8e38a
Revises: 4e4f3fba9a9a
Create Date: 2025-12-21 15:29:30.956567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6e180c8e38a'
down_revision: Union[str, None] = '4e4f3fba9a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('closed', sa.BOOLEAN(), nullable=False))
    op.alter_column('accounts', 'type',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_accounts_type'), table_name='accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_accounts_type'), 'accounts', ['type'], unique=False)
    op.alter_column('accounts', 'type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('accounts', 'closed')
    # ### end Alembic commands ###
