"""adds import_id to plan

Revision ID: f3625cfdad88
Revises: bfba9d607088
Create Date: 2025-12-20 23:32:21.477961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3625cfdad88'
down_revision: Union[str, None] = 'bfba9d607088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('import_id', sa.TEXT(), nullable=True))
    op.create_index(op.f('ix_plans_import_id'), 'plans', ['import_id'], unique=True)
    op.drop_column('plans', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('amount', sa.NUMERIC(precision=17, scale=3), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_plans_import_id'), table_name='plans')
    op.drop_column('plans', 'import_id')
    # ### end Alembic commands ###
