"""add cleared

Revision ID: f6f05cc3682d
Revises: d6e180c8e38a
Create Date: 2025-12-21 15:57:25.765756

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6f05cc3682d"
down_revision: Union[str, None] = "d6e180c8e38a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("matched_transaction_id", sa.UUID(), nullable=True)
    )
    op.add_column("transactions", sa.Column("cleared", sa.TEXT(), nullable=True))
    op.add_column("transactions", sa.Column("approved", sa.BOOLEAN(), nullable=False))
    op.add_column(
        "transactions", sa.Column("parent_transaction_id", sa.UUID(), nullable=True)
    )
    op.create_foreign_key(
        "transaction_matched_transaction_fkey",
        "transactions",
        "transactions",
        ["matched_transaction_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "transaction_parent_transaction_fkey",
        "transactions",
        "transactions",
        ["parent_transaction_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
    op.execute("ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "transaction_parent_transaction_fkey", "transactions", type_="foreignkey"
    )
    op.drop_constraint(
        "transaction_matched_transaction_fkey", "transactions", type_="foreignkey"
    )
    op.drop_column("transactions", "parent_transaction_id")
    op.drop_column("transactions", "approved")
    op.drop_column("transactions", "cleared")
    op.drop_column("transactions", "matched_transaction_id")
    # ### end Alembic commands ###
